---
#- name: Multi-Switch Single Switch Setup

#*** Version 0.1.0

#*** Configure the multi-switch lab for a single-switch test
#***  by setting appropriate interfaces up/down.
#***  Note that it is really important to get this right as
#***  otherwise loops can form which will put switches to 100% CPU

#*** Switch 1:
- hosts: switch1

  tasks:

    - name: eth1 up
      command: "sudo ip link set dev eth1 up"

    - name: eth1 OVS add
      command: "sudo ovs-vsctl add-port br0 eth1"
      ignore_errors: True

    - name: eth2 down
      command: "sudo ip link set dev eth2 down"

    - name: eth2 OVS del
      command: "sudo ovs-vsctl del-port br0 eth2"
      ignore_errors: True

    - name: eth3 up
      command: "sudo ip link set dev eth3 up"

    - name: eth3 OVS add
      command: "sudo ovs-vsctl add-port br0 eth3"
      ignore_errors: True

    - name: eth5 up
      command: "sudo ip link set dev eth5 up"

    - name: eth5 OVS add
      command: "sudo ovs-vsctl add-port br0 eth5"
      ignore_errors: True

    - name: eth6 down
      command: "sudo ip link set dev eth6 down"

    - name: eth6 OVS del
      command: "sudo ovs-vsctl del-port br0 eth6"
      ignore_errors: True

    - name: eth7 up
      command: "sudo ip link set dev eth7 up"

    - name: eth7 OVS add
      command: "sudo ovs-vsctl add-port br0 eth7"
      ignore_errors: True

    - name: Set OpenFlow Controller On
      command: "sudo ovs-vsctl set-controller br0 tcp:172.16.0.3:6633"


#*** Switch 2:
- hosts: switch2

  tasks:

    - name: eth3 down
      command: "sudo ip link set dev eth3 down"

    - name: Set OpenFlow Controller Off
      command: "sudo ovs-vsctl set-controller br0 tcp:1.1.1.1:6633"

#*** Switch 3:
- hosts: switch3

  tasks:

    - name: eth3 down
      command: "sudo ip link set dev eth3 down"

    - name: Set OpenFlow Controller Off
      command: "sudo ovs-vsctl set-controller br0 tcp:1.1.1.1:6633"

#*** Switch 4:
- hosts: switch4

  tasks:

    - name: eth3 down
      command: "sudo ip link set dev eth3 down"

    - name: Set OpenFlow Controller Off
      command: "sudo ovs-vsctl set-controller br0 tcp:1.1.1.1:6633"

#*** Switch 5:
- hosts: switch5

  tasks:

    - name: Set OpenFlow Controller Off
      command: "sudo ovs-vsctl set-controller br0 tcp:1.1.1.1:6633"

#*** Switch n:
- hosts: switchn

  tasks:

    - name: eth3 down
      command: "sudo ip link set dev eth3 down"

    - name: Set OpenFlow Controller Off
      command: "sudo ovs-vsctl set-controller br0 tcp:1.1.1.1:6633"

- hosts: clients

  tasks:

    #*** Bail out of test if PING fails:
    - name: send PING to server to check connectivity
      shell: "ping -c 1 sv1"

- hosts: load-generators

  tasks:

    #*** Bail out of test if PING fails:
    - name: send PING to server to check connectivity
      shell: "ping -c 1 lr1"
