---
#- name: Check Syslog for Regression Tests for nmeta

#*** Version 0.1.0

#*** Move nmeta syslog file to .old and touch a new one so that
#*** nmeta logs can be analysed post test for undesirable log
#*** entries that indicate a condition that should be fixed
#*** Pass it a results_dir variable

#*** Example nmeta baseline:
#***   ansible-playbook ~/automated_tests/nmeta-full-regression-logcheck-template.yml --extra-vars "results_dir=~/results/regression/nmeta-full/20160922222553/"

- hosts: controllers

  tasks:

    - name: remove old output
      shell: "rm /tmp/logcheck.txt"
      ignore_errors: True

    - name: grep syslog for specific events to file
      shell: "egrep 'sev=CRITICAL|sev=WARNING' /var/log/nmeta > /tmp/logcheck.txt"

    - name: Retrieve log output
      fetch: src=/tmp/logcheck.txt dest={{ results_dir }} flat=yes
